#!/bin/bash 
#echo "Script executed from: ${PWD}"
PARENTDIR="$PWD"
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#BASEDIR1=$(dirname $0)
#echo "Script location: ${BASEDIR}"
#echo "Script location: ${BASEDIR1}"
#node bank.js "$@" "-x" "$PWD";
#echo "Script executed from: ${PWD}"
node "${BASEDIR}"/bank.js "$@" "-x" "$PARENTDIR"
